name: Clone, Build and Release Bruno Client

on:
  schedule:
    - cron: "0 18 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: usebruno/bruno
          path: bruno
          ref: main
          fetch-depth: 1

      - name: Checkout patch repository
        uses: actions/checkout@v3
        with:
          repository: 9uanhuo/workers
          path: gh-workers
          ref: main
          fetch-depth: 1

      - name: Get some infos
        working-directory: ./bruno
        run: |
          BRUNO_VERSION=$(cat packages/bruno-electron/package.json | jq -r '.version')
          CUR_DATE=$(date +%Y%m%d)
          echo "BRUNO_VERSION=${BRUNO_VERSION}" >> $GITHUB_ENV
          echo "CUR_DATE=${CUR_DATE}" >> $GITHUB_ENV
          echo "Current Bruno version is ${BRUNO_VERSION}"
          echo "Current Date is ${CUR_DATE}"

      - name: Apply patch
        working-directory: ./bruno
        run: |
          cat ../gh-workers/patches/bruno.patch
          git apply ../gh-workers/patches/bruno.patch

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./bruno
        run: npm i --legacy-peer-deps

      - name: Build Bruno Client
        working-directory: ./bruno
        run: |
          npm run build:graphql-docs
          npm run build:bruno-query
          npm run build:bruno-common
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js
          npm run build:web

      - name: Package Bruno Client for macOS
        working-directory: ./bruno
        run: npm run build:electron:mac

      - name: Upload build artifact for x64 macOS
        uses: actions/upload-artifact@v4
        with:
          name: bruno_${{ env.CUR_DATE }}_${{ env.BRUNO_VERSION }}_x64_mac
          path: ./bruno/packages/bruno-electron/out/*x64_mac.dmg

      - name: Upload build artifact for arm64 macOS
        uses: actions/upload-artifact@v4
        with:
          name: bruno_${{ env.CUR_DATE }}_${{ env.BRUNO_VERSION }}_arm64_mac
          path: ./bruno/packages/bruno-electron/out/*arm64_mac.dmg
